# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 00:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('document', models.FileField(default=False, upload_to='articles/')),
            ],
        ),
        migrations.CreateModel(
            name='Minicurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mini_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=400)),
                ('professor', models.CharField(max_length=100)),
                ('begin', models.DateTimeField()),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('instituicao', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('comprovante', models.FileField(default=False, upload_to='comprovantes/')),
                ('modalidade', models.CharField(choices=[('GRA', 'Estudante de Graduação'), ('PGR', 'Estudante de Pós-Graduação'), ('PRO', 'Profissional')], default=False, max_length=3)),
                ('minicursos', models.ManyToManyField(to='site_functions.Minicurso')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_functions.UserProfile'),
        ),
    ]
