# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_functions', '0002_auto_20170306_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minicurso',
            name='mini_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='comprovante',
            field=models.ImageField(default=False, upload_to='comprovantes/'),
        ),
    ]
