# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_functions', '0005_auto_20170309_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='had_paid',
            field=models.BooleanField(default=False),
        ),
    ]
