# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_functions', '0006_userprofile_had_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cpf',
            field=models.CharField(default=False, max_length=11),
        ),
    ]
