# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_functions', '0007_auto_20170310_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='site_functions.UserProfile'),
        ),
    ]
