# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_functions', '0009_auto_20170310_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='cpf',
        ),
    ]
