# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import site_functions.validators


class Migration(migrations.Migration):

    dependencies = [
        ('site_functions', '0011_auto_20170314_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='comprovante',
            field=models.FileField(default=False, upload_to='certificados/', validators=[site_functions.validators.validate_article_type]),
        ),
    ]
