# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_functions', '0012_auto_20170317_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='area',
            field=models.CharField(choices=[('AR1', 'Área 1'), ('AR2', 'Área 2'), ('AR3', 'Área 3'), ('AR4', 'Área 4')], default=False, max_length=3),
        ),
        migrations.AddField(
            model_name='article',
            name='autores',
            field=models.TextField(default=False, max_length=300),
        ),
    ]
