# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import site_functions.validators


class Migration(migrations.Migration):

    dependencies = [
        ('site_functions', '0015_auto_20170328_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='certificado',
            field=models.FileField(default=False, upload_to='certificados/', validators=[site_functions.validators.validate_article_type]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='comprovante',
            field=models.ImageField(default=False, upload_to='comprovantes/'),
        ),
    ]
