# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_functions', '0017_talk'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='talk_local',
            field=models.CharField(default=False, max_length=256),
        ),
        migrations.AddField(
            model_name='talk',
            name='talk_speaker_lattes',
            field=models.CharField(default=False, max_length=256),
        ),
        migrations.AddField(
            model_name='talk',
            name='talk_speaker_photo',
            field=models.ImageField(default=False, upload_to='palestrantes/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='area',
            field=models.CharField(choices=[('QOR', 'Química Orgânica'), ('QIN', 'Química Inorgânica'), ('FSQ', 'Fisico-Química'), ('QAN', 'Química Analítica'), ('QAM', 'Química Ambiental'), ('EAQ', 'Educação Aplicada à Química'), ('ENG', 'Engenharia'), ('MAT', 'Materiais'), ('ALM', 'Alimentos'), ('TCF', 'Tecnologia Farmacêutica')], default=False, max_length=3),
        ),
    ]
