# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_functions', '0018_auto_20170505_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='talk_local',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='talk',
            name='talk_speaker_lattes',
            field=models.CharField(default='', max_length=256),
        ),
    ]
