# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_functions', '0019_auto_20170511_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='minicurso',
            name='short_course_cover',
            field=models.ImageField(default=False, upload_to=b'minicursos/'),
        ),
    ]
