# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_functions', '0021_auto_20170519_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minicurso',
            name='description',
            field=models.TextField(max_length=6048),
        ),
        migrations.AlterField(
            model_name='talk',
            name='talk_description',
            field=models.CharField(max_length=8128),
        ),
    ]
