# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 00:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_functions', '0021_auto_20170517_1412'),
        ('site_functions', '0021_auto_20170519_0910'),
    ]

    operations = [
    ]
