# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_functions', '0022_auto_20170519_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='have_home',
            field=models.BooleanField(default=False),
        ),
    ]
