# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_functions', '0022_merge_20170520_2146'),
        ('site_functions', '0022_auto_20170519_2226'),
    ]

    operations = [
    ]
