# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-19 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_functions', '0023_merge_20170520_2149'),
        ('site_functions', '0024_auto_20170521_1243'),
    ]

    operations = [
    ]
