# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_functions', '0026_auto_20170919_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='curso',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='local_de_atuacao',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profissao',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='instituicao',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='modalidade',
            field=models.CharField(choices=[('EST', 'Estudante'), ('PRO', 'Profissional')], default=False, max_length=3),
        ),
    ]
