# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_functions', '0028_auto_20170919_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='conclusao',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='article',
            name='introducao',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='article',
            name='metodologia',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='article',
            name='objetivo',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='article',
            name='originalidade',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='article',
            name='resultados',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='article',
            name='titulo',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
