# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-21 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_functions', '0029_auto_20170919_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='revision',
            field=models.TextField(default=False, max_length=300),
        ),
    ]
