# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-21 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_functions', '0030_article_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='originalidade',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
