# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-04 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_functions', '0032_auto_20171004_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='curso',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='instituicao',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='local_de_atuacao',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profissao',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
