from django.conf.urls import include, url
from . import views

urlpatterns = [
 	url(r'^$', views.home, name='home'),
    url(r'^register/$', views.register, name='register'),
    url(r'^recover_password/$', views.recover_password, name='recover_password'),
    url(r'^register_admin/$', views.admin_register, name='admin_register'),
    url(r'^list_admins/$', views.list_admins, name='list_admins'),
    url(r'^user_details/(?P<user_id>[0-9]+)$', views.user_detail, name='user_detail'),
    url(r'^schedule/$', views.schedule, name='schedule'),
    url(r'^pdf_gen/$', views.pdf_gen, name='pdf_gen'),
    url(r'^lista_presenca/$', views.lista_presenca, name='lista_presenca'),
    #url(r'^upload_receipt/(?P<user_id>[0-9]+)$', views.upload_receipt, name='upload_receipt'),
    #url(r'^upload_article/(?P<user_id>[0-9]+)$', views.upload_article, name='upload_article'),
    url(r'^upload_certificate/(?P<user_id>[0-9]+)$', views.upload_certificate, name='upload_certificate'),
    url(r'^login/$', views.user_login, name='user_login'),
    url(r'^logout/$', views.user_logout, name='user_logout'),
    #url(r'^short_course_register/$', views.register_short_course, name='register_short_course'),
    #url(r'^short_course_details/(?P<short_course_id>[0-9]+)$', views.short_course_detail, name='short_course_detail'),
    #url(r'^short_course_users/(?P<short_course_id>[0-9]+)$', views.list_users_by_sc, name='list_users_by_sc'),
    url(r'^talk_details/(?P<talk_id>[0-9]+)$', views.talk_detail, name='talk_detail'),
    #url(r'^edit_short_course/(?P<short_course_id>[0-9]+)$', views.edit_short_course, name='edit_short_course'),
    url(r'^edit_talk/(?P<talk_id>[0-9]+)$', views.edit_talk, name='edit_talk'),
    #url(r'^mark_payment/(?P<user_id>[0-9]+)$', views.mark_payment, name='mark_payment'),
    url(r'^list_users/(?P<page>[0-9]+)$', views.list_students, name='list_users'),
    #url(r'^sc_editions/$', views.list_short_courses, name='list_short_courses'),
    url(r'^talk_editions/$', views.list_talks, name='list_talks'),
    #url(r'^accept_article/(?P<user_id>[0-9]+)/(?P<article_id>[0-9]+)$', views.accept_article, name='accept_article'),
    url(r'^download/(?P<path>.*)$', views.download, name='download'),
    url(r'^confirm/(?P<confirmation_code>.*)/(?P<user_id>[0-9]+)$', views.confirm, name='confirm'),
    url(r'^alterate/(?P<user_id>[0-9]+)$', views.alterate, name='alterate'),
    url(r'^new_pass/(?P<confirmation_code>.*)/(?P<user_id>[0-9]+)$', views.new_pass, name='new_pass'),
    url(r'^talk_register/$', views.register_talk, name='register_talk'),
    url(r'^del_user/(?P<user_id>[0-9]+)$', views.del_student, name='del_user'),
]
